export const TabNav = {
  Home: 'Home',
  Profile: 'Profile',
  Save: 'Save',
  Menu: 'Menu',
};

export const StackNav = {
  Auth: 'Auth',
  TabBar: 'TabBar',
  Splash: 'Splash',
  Connect: 'Connect',
  Login: 'Login',
  SignUp: 'SignUp',
  Cart: 'Cart',
  OnBoarding: 'OnBoarding',
  OnBoarding2: 'OnBoarding2',
  OtpVerification: 'OtpVerification',
  ForgotPassword: 'ForgotPassword',
  NewPassword: 'NewPassword',
  ProductList: 'ProductList',
  ProductDetail: 'ProductDetail',
  CreateMyPack: 'CreateMyPack',
  CreateBundleDetails: 'CreateBundleDetails',
  CheckOut: 'CheckOut',
  OrderPage: 'OrderPage',
  Search: 'Search',
  MyOrder: 'My Order',
  OrderDetails: 'My Order Details',
  OfferAndPromos: 'Offer And Promos',
  CouponDetails: 'Coupon Details',
  DeliveryAddress: 'Delivery Address',
  SelectInterest: 'SelectInterest',
  SetPin: 'SetPin',
  SetUpProfile: 'SetUpProfile',
  SetSecure: 'SetSecure',
  ForgotPasswordOtp: 'ForgotPasswordOtp',
  CreateNewPassword: 'CreateNewPassword',
  Privacy: 'Privacy',
  PrivacyPolicy: 'PrivacyPolicy',
  HelpCenter: 'HelpCenter',
  Security: 'Security',
  Language: 'Language',
  Birthday: 'Birthday',
  Gender: 'Gender',
  Setting: 'Setting',
  EditProfile: 'EditProfile',
  Message: 'Message',
  Chat: 'Chat',
  Call: 'Call',
  Sound: 'Sound',
  Report: 'Report',
  ProfileDetail: 'ProfileDetail',
  Suggested: 'Suggested',
  Following: 'Following',
  Follower: 'Follower',
  ManageAccount: 'ManageAccount',
  QrCode: 'QrCode',
  SoundCategory: 'SoundCategory',
  HashtagCategory: 'HashtagCategory',
  TrendingSound: 'TrendingSound',
  TrendingHashtag: 'TrendingHashtag',
  Search: 'Search',
  SearchTop: 'SearchTop',
  SearchVideo: 'SearchVideo',
  SearchSound: 'SearchSound',
  SearchUser: 'SearchUser',
  SearchLive: 'SearchLive',
  SearchHashtag: 'SearchHashtag',
  UserNetwork: 'UserNetwork',
  PostDetail: 'PostDetail',
  PostSound: 'PostSound',
  ReelsComponent: 'ReelsComponent',
  FindFriends: 'FindFriends',
  Live: 'Live',
  NewAddress: 'NewAddress',
  EditProfile: 'EditProfile',
  ChangePassword: 'ChangePassword',
  ChangePhoneNumber: 'ChangePhoneNumber',
  Notification: 'Notification',
  SelectLanguage: 'SelectLanguage',
  Setting: 'Setting',
  Payment: 'Payment',
  AddNewCard: 'AddNewCard',
  AboutUs: 'AboutUs',
  ContactUs: 'ContactUs',
  Faq: 'Faq',
  Help: 'Help',
  TermAndConditions: 'TermAndConditions',
  Review: 'Review',
};
